### ISSUE TITLE
about gulp instalation in ubuntu 16

### ISSUE THREAD

**Issue by eduardo-g-silva** [antoniocarboni/magento2-gulp#1]
Hi thanks to share the code I am having some issues installing gulp maybe you know whats wrong.

After the npm installation i  get:
`Error: Cannot find module 'gulp-task-loader'`

So i install manually the module using:
`npm install 'gulp-task-loader'`

Then on gulp install i get:
`Error: ENOENT: no such file or directory, lstat 'falsegulp-tasks'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at loadTasks (/var/www/wl/comesconnected/htdocs/vendor/antoniocarboni/magento2-gulp/node_modules/gulp-task-loader/index.js:70:18)
    at module.exports (/var/www/wl/comesconnected/htdocs/vendor/antoniocarboni/magento2-gulp/node_modules/gulp-task-loader/index.js:83:2)
    at Object.<anonymous> (/var/www/wl/comesconnected/htdocs/vendor/antoniocarboni/magento2-gulp/gulpfile.js:479:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`
I tried many things but I wasn't able to make it work do you have any idea what can be the problem?

**Comment by adamgilmour** [comment]
Same issue here, this doesn't work :(

**Comment by wontroba666** [comment]
yes. unfortunatelly not works

**Comment by to8gal** [comment]
exactly same here, XAMPP 7.0.30 on osx High Sierra Magento 2.2.4,

sokution anyone?
